name: ci_01

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-lastest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-vertion: '17'
        distributionn: 'adopt'
    - name: Build with gradle
      run: ./gradlew build
